### ISSUE TITLE
I'm not sure how to actually use this anymore

### ISSUE THREAD

**Issue by DavidJHartman** [sainteos/tmxparser#28]
With the new update a week ago, I'm not sure how to actually use it. The example is pretty detailed, but I'm not actually sure what to do with this. If you could, I'd like a step by step of what to do from parsing the .tmx to render. (I'm using sfml, in case you care).

**Comment by aquafox** [comment]
What exactly don't you get? I just read the example .cpp today and it basically does everything you need. You can even copy/paste.

**Comment by Bill-Cosby** [comment]
If you'll check my previous post, I have the example. I read it and everything, but how do I draw the tiles? Hell, I don't even care about properties yet. I just want to know how to set up my program to display pretty pictures.

**Comment by aquafox** [comment]
tmxparser gets map information from a tmx file for you. It's up to you to render them. Might I suggest looking up how to render spritesheets on SFML. Your problem is outside of the scope of this project. Might I suggest reading [this](http://www.sfml-dev.org/tutorials/2.3/graphics-vertex-array.php) to get you started?

**Comment by Bill-Cosby** [comment]
I know how to take the picture and draw individual tiles from it, but I don't want to code every specific coordinate for 42+ tiles. I don't know if .tmx stores a tile's position on a spritesheet.

**Comment by aquafox** [comment]
Tiles are placed in a grid system. There is a for loop in the example where they get information of tiles in a layer. I think there is a serious lack of knowledge here when it comes to programming. Please understand what tmx is first before assuming this library can draw anything for you. [Here are the specifications](http://doc.mapeditor.org/reference/tmx-map-format/) of tmx format.

**Comment by aquafox** [comment]
In response to the coordinates, well when you get tile info through the loop draw them out in the grid by order (or render order which you pull from tmx) and tmx will tell you the tileset gid (which tile exactly to draw there).

**Comment by georgerbr** [comment]
tmxparser only parses TMX files, and does not know nor care about rendering. That is actually a good thing, because we can keep dependencies down to a minimum and you gain flexibility. Just write your own rendering module - you can use SFML, SDL, or just about anything else you like.
If you don't want to code the rendering part yourself, consider trying [sfml-tmxloader](https://github.com/fallahn/sfml-tmxloader).

**Comment by Bill-Cosby** [comment]
I appreciate your help. I am well aware that this library isn't for rendering. I am using sfml. I was using a  different library to parse .tmx and it was just fine, I just had to set up every individual tile and give them all intRects to render specific tiles instead of the whole tileset. I don't want to do that with huge tilesets, and so I just want to know if .tmx stores where the tile is on the tileset. I know how to render them, I just don't know how to give the tiles the correct picture.

**Comment by georgerbr** [comment]
I think you're a bit confused about how the library is designed. Take a look at the diagram I uploaded in #17; it's a bit outdated, but a good starting point.

You don't need to know where the tile is on the tileset; rather you need to know where the tile is on the layer. `test.cpp` does what you want: iterate through the `i` rows and `j` columns of each layer and render the appropriate tile at each position. The difference is that while in text mode we just `printf()` the tile, in SFML/SDL you'd use the `tile_width` and `tile_heigth` of the tileset to calculate the offset before rendering.

**Comment by Bill-Cosby** [comment]
For some reason now I'm getting undefined reference errors without editing the example??

**Comment by aquafox** [comment]
Did you link tinyxml2?

**Comment by richelbilderbeek** [comment]
@Bill-Cosby : for direct rendering one could use [sfml-tmxloader](https://github.com/fallahn/sfml-tmxloader) or [STP](https://github.com/edoren/STP). At the moment, both -at least on my computers- do not work, probably caused by something upstream. But perhaps those suit your needs better.
