### ISSUE TITLE
Static library?

### ISSUE THREAD

**Issue by LeoTindall** [sainteos/tmxparser#40]
I'd like to include this library in a multi-platform project. Is there a simple way to compile this library as a static library for Linux, Windows, Mac OS X? Thank you.

**Comment by sainteos** [comment]
The README has instructions for how to build this library (giving you both static and dynamic libraries to work with) that works for linux and osx. As far as a windows build, I know it is possible to compile for windows because I set up a cross-compile, but I had to do some work to get it to build correctly. Right now Windows building is not officially supported.
